### ISSUE TITLE
NPE during authentication

### ISSUE THREAD

**Issue by jefftharris** [box/box-android-sdk#282]
I'm getting a number of crash reports with people trying to authenticate to Box.  Unfortunately, I'm not able to recreate with my account.  A user did mention that they had reset their password.  I'm using 4.0.8.

java.lang.NullPointerException: 
  at com.eclipsesource.json.JsonObject.indexOf(JsonObject.java:628)
  at com.eclipsesource.json.JsonObject.set(JsonObject.java:482)
  at com.eclipsesource.json.JsonObject.set(JsonObject.java:455)
  at com.box.androidsdk.content.models.BoxJsonObject$CacheMap.set(BoxJsonObject.java:323)
  at com.box.androidsdk.content.models.BoxJsonObject.set(BoxJsonObject.java:124)
  at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.setBaseDomain(BoxAuthentication.java:704)
  at com.box.androidsdk.content.auth.OAuthActivity.startMakingOAuthAPICall(OAuthActivity.java:380)
  at com.box.androidsdk.content.auth.OAuthActivity.onReceivedAuthCode(OAuthActivity.java:175)
  at com.box.androidsdk.content.auth.OAuthActivity.onReceivedAuthCode(OAuthActivity.java:165)
  at com.box.androidsdk.content.auth.OAuthWebView$OAuthWebViewClient.onPageStarted(OAuthWebView.java:167)
  at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:532)
  at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:157)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7231)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by doncung** [comment]
Looking at the logic in JsonObject not sure how this can happen, but I did make a change that sure prevent this code flow from appearing. 

https://github.com/box/box-android-sdk/pull/286/files

Once this is merged in the setBaseDomain method should no longer be getting called. Please let us know if you are still experiencing the issue after that.

**Comment by jefftharris** [comment]
When the next version is released, I'll update the app with it and watch for any more crash reports.

**Comment by doncung** [comment]
4.0.9 should include this change.

**Comment by jefftharris** [comment]
My users are still experiencing this issue with 4.0.9.  Investigating further, it appears that something is not correct with the serialization of the BoxAuthentication.BoxAuthenticationInfo class that is serialized in the OAuthActivity.

**Comment by ashughes** [comment]
I'm seeing this issue as well in 4.0.11, although it's hidden behind an "Authentication Failed" toast produced in `OAuthActivity.onAuthFailure()`.

**Comment by jefftharris** [comment]
See my comment here for a fix - https://github.com/box/box-android-sdk/issues/308#issuecomment-333405568
