### ISSUE TITLE
box android sdk crash issue in release config

### ISSUE THREAD

**Issue by niranjan1993** [box/box-android-sdk#308]
Hello,

I am using Proguard to obfuscate code for release configuration in our app.In the release build the app crashes after clicking on **grant access to box** button after the authentication is successful with the following error "Unfortunately, eSign PDF has stopped" and error log mentioned below.

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.a.a.d$a.a(java.lang.Object)' on a null object reference 
at com.a.a.d.d(Unknown Source) 
at com.a.a.d.b(Unknown Source) 
at com.a.a.d.b(Unknown Source) 
at com.box.androidsdk.content.b.t$b.a(Unknown Source) 
at com.box.androidsdk.content.b.t.a(Unknown Source) 
at com.box.androidsdk.content.auth.c$d.d(Unknown Source) 
at com.box.androidsdk.content.auth.OAuthActivity.b(Unknown Source) 
at com.box.androidsdk.content.auth.OAuthActivity.a(Unknown Source) 
at com.box.androidsdk.content.auth.OAuthActivity.a(Unknown Source) 
at com.box.androidsdk.content.auth.OAuthWebView$c.onPageStarted(Unknown Source) 
at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:190) 
at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:20) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5343) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
I know the issue is because of code obfuscation,but can you please tell what all classes related to box i can add in my proguard rules so i can avoid this issue.

Thank you

**Comment by jefftharris** [comment]
This issue may be related to issue 282, if this trace decodes to:
at com.eclipsesource.json.JsonObject.indexOf(JsonObject.java:628)
at com.eclipsesource.json.JsonObject.set(JsonObject.java:482)
at com.eclipsesource.json.JsonObject.set(JsonObject.java:455)
at com.box.androidsdk.content.models.BoxJsonObject$CacheMap.set(BoxJsonObject.java:323)

**Comment by jefftharris** [comment]
This issue and also 282 may have been caused by ProGuard stripping Serializable fields from the Box classes in a release build.  Adding the following lines to my proguard-rules.pro fixed the issue for me.  Perhaps the SDK should come with an appropriate rules file and instructions for integrating with apps.

```
-keepnames class * implements java.io.Serializable

-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
```

**Comment by niranjan1993** [comment]
Thanks @jefftharris, i was able to fix this issue.
