### ISSUE TITLE
Grant access to box always failed, NPE was thrown

### ISSUE THREAD

**Issue by jlcoa** [box/box-android-sdk#314]
Hello, 
I tried to integrate box into my app, but I always get onAuthFailure result. Could you help to figure out what should I do to fix this issue?
 1. The configuration:
     build.gradle:<br />
         <code>ext {
              compileSdkVersion=26
              buildToolsVersion="26.0.0"
              minSdkVersion =19
              targetSdkVersion =26
              preDexLibs = !project.hasProperty('disablePreDex')
          }
          dependencies {compile 'com.box:box-android-sdk:4.0.10'}</code>
 progurad.cfg:<br/>
      <code> -keep class com.box.androidsdk.**  { *; }
       -keep interface com.box.androidsdk.**  { *; }
       -dontwarn com.box.androidsdk.**</code><br/>
 2. The Auth code:
<code>BoxConfig.IS_LOG_ENABLED = true;
  BoxConfig.CLIENT_ID = BUILD.CloudStorage.Box.CLIENT_ID;
  BoxConfig.CLIENT_SECRET = BUILD.CloudStorage.Box.CLIENT_SECRET;
  BoxSession mSession = new BoxSession(this);
  mSession.setSessionAuthListener(this);
  mSession.authenticate(getApplicationContext());</code><br/>
3. The login screen can be displayed correctly. After enter email and password, will go to grant access to box screen, after click the allow button, an error got: 
<code>java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.eclipsesource.json.JsonObject$HashIndexTable.get(java.lang.Object)' on a null object reference
at java.util.concurrent.FutureTask.report(FutureTask.java:94)
at java.util.concurrent.FutureTask.get(FutureTask.java:164)
at com.box.androidsdk.content.auth.OAuthActivity$3.run(OAuthActivity.java:388)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.eclipsesource.json.JsonObject$HashIndexTable.get(java.lang.Object)' on a null object reference
10-13 15:47:00.055 3669-24419/? V/WindowManager: Relayout Window{5bceabdd0 u0 com.ringcentral.android/com.box.androidsdk.content.auth.OAuthActivity}: viewVisibility=0 req=1440x2560 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=1 fl=#1810100 pfl=0x20000 wanim=0x10303ea vsysui=0x400 needsMenuKey=2 naviIconColor=0}
at com.eclipsesource.json.JsonObject.indexOf(JsonObject.java:628)
at com.eclipsesource.json.JsonObject.get(JsonObject.java:528)
 at com.box.androidsdk.content.models.BoxJsonObject$CacheMap.getAsJsonValue(BoxJsonObject.java:558)
at com.box.androidsdk.content.models.BoxJsonObject$CacheMap.getAsString(BoxJsonObject.java:315)
at com.box.androidsdk.content.models.BoxJsonObject.getPropertyAsString(BoxJsonObject.java:120)
at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.getBaseDomain(BoxAuthentication.java:718)
at com.box.androidsdk.content.auth.BoxApiAuthentication.getBaseUri(BoxApiAuthentication.java:41)
at com.box.androidsdk.content.auth.BoxApiAuthentication.getTokenUrl(BoxApiAuthentication.java:79)
at com.box.androidsdk.content.auth.BoxApiAuthentication.createOAuth(BoxApiAuthentication.java:59)
at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:343)
at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:339)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)</code><br/>
4. Checked the code, the error happened at BoxApiAuthentication.getBaseUri(), the 
mSession.getAuthInfo().getBaseDomain() met the Nullpoint issue, due to the JsonObject's HashIndexTable is empty.
In OAuthActivity.createOAuthActivityIntent(), the JsonObject's HashIndexTable is not null in the session, but after transfer to OAuthActivity.onCreate(), the value become null.

**Comment by jefftharris** [comment]
See my comment here for a fix - https://github.com/box/box-android-sdk/issues/308#issuecomment-333405568

**Comment by PreciselyAlyss** [comment]
Please reopen if you find the information on issue #308 didn't help
