### ISSUE TITLE
Can not download small document file.

### ISSUE THREAD

**Issue by manhphi65** [box/box-android-sdk#317]
First, sorry for my bad English.
I followed this doc to download file using box-android-sdk.
https://github.com/box/box-android-sdk/blob/master/doc/Files.md
Everythings ok. It is not work with small file .
This is my code : 
```
            BoxDownload fileDownload = mBoxApiFile.getDownloadRequest(localFile, fileId)
                    .setProgressListener(new ProgressListener() {
                        @Override
                        public void onProgressChanged(long numBytes, long totalBytes) {
                            if (((int) (numBytes / (totalBytes / 100))) > progress) {
                                progress = (int) (numBytes / (totalBytes / 100));
                                publishProgress(progress);
                            }
                        }
                    })
                    .setContentType(BoxRequest.ContentTypes.URL_ENCODED)
                    .send();
```

When i download a Text file 11KB, it is ok. But when i download "6Byte txt file" it throw Exception : 
at (DownloadBoxFileService.java:161) [downLoadFile]com.box.androidsdk.content.BoxException: Couldn't connect to the Box API due to a network error.
                                                                                        at com.box.androidsdk.content.requests.BoxHttpResponse.getBody(BoxHttpResponse.java:123)
                                                                                        at com.box.androidsdk.content.requests.BoxHttpResponse.getBody(BoxHttpResponse.java:94)
                                                                                        at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:399)
                                                                                        at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:282)
                                                                                        at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:238)
                                                                                        at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:190)
                                                                                        at filemanager.services.download.DownloadBoxFileService.downLoadFile(DownloadBoxFileService.java:145)
                                                                                        at filemanager.services.download.DownloadBoxFileService.onHandleIntent(DownloadBoxFileService.java:94)
                                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     Caused by: java.net.SocketException: Socket is closed
                                                                                        at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
                                                                                        at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
                                                                                        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:743)
                                                                                        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
                                                                                        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                                        at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                                                        at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
                                                                                        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:360)
                                                                                        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
                                                                                        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:261)
                                                                                        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:253)
                                                                                        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:162)
                                                                                        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
                                                                                        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:89)
                                                                                        at com.box.androidsdk.content.requests.BoxHttpResponse.getBody(BoxHttpResponse.java:119)
                                                                                        at com.box.androidsdk.content.requests.BoxHttpResponse.getBody(BoxHttpResponse.java:94) 
                                                                                        at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:399) 
                                                                                        at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:282) 
                                                                                        at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:238) 
                                                                                        at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:190) 
                                                                                        at filemanager.services.download.DownloadBoxFileService.downLoadFile(DownloadBoxFileService.java:145) 
                                                                                        at filemanager.services.download.DownloadBoxFileService.onHandleIntent(DownloadBoxFileService.java:94) 
                                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nidoran** [comment]
Hi @manhphi65

I tried code very similar to your example (with the latest Box SDK code) in my environment and wasn't able to reproduce. Based on your stack trace, it looks like it's hitting a network, socket, or SSL-related error.

If you're still having this issue, could you add some details about your environment such as what version of Android/API level it's using?

Thanks!
