### ISSUE TITLE
NPE when trying to download a thumbnail

### ISSUE THREAD

**Issue by mvysny** [box/box-android-sdk#342]
Hi, I'm trying to download a thumbnail with the SDK 4.0.11, unfortunately it doesn't work and fails with:
```
                            Caused by: java.lang.NullPointerException
                               at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:406)
                               at com.box.androidsdk.content.requests.BoxRequestDownload$DownloadRequestHandler.onResponse(BoxRequestDownload.java:282)
                               at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:238)
                               at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:190)

```

**Comment by doncung** [comment]
Can you add the code you are using to download the thumbnail? There are two ways this can be done now (via representations or via the older thumbnails endpoint)

**Comment by mvysny** [comment]
Certainly. I'm trying to use the `BoxApiFile.getDownloadThumbnailRequest()` as follows:
```
        val api = BoxApiFile(session)
        val result = api.getDownloadThumbnailRequest(directory, file.id).apply {
            format = BoxRequestsFile.DownloadThumbnail.Format.JPG
            val size = SIZES.pickBestThumbnailSize().id
            minWidth = size
            minHeight = size
            maxWidth = size
            maxHeight = size
        }.send()
```

**Comment by doncung** [comment]
Thanks. I think I see what the problem is. For now you can work around this by calling this with a file object (needs to exist) instead of a directory object. I'll make a change for this shortly.

**Comment by mvysny** [comment]
Thanks for the tip. You're right: when `getDownloadThumbnailRequest` is called with a file, it works and it downloads the thumbnail properly.

**Comment by doncung** [comment]
Ok I've made a pull request that will warn earlier now. For the thumbnails endpoint we don't get a content disposition from the server so we can't automatically create a file for you unlike with downloading content. As such you will need to pass in the file yourself.
