### ISSUE TITLE
Exception Upload File Session （Java Basic Exception）

### ISSUE THREAD

**Issue by kbboss** [box/box-android-sdk#382]
`Process: com.box.androidsdk.sample, PID: 32218
                                                                           java.lang.StringIndexOutOfBoundsException: length=1; regionStart=0; regionLength=3
                                                                               at java.lang.String.substring(String.java:1931)
                                                                               at com.box.androidsdk.content.utils.BoxDateFormat.getTimeZone(BoxDateFormat.java:63)
                                                                               at com.box.androidsdk.content.utils.BoxDateFormat.parse(BoxDateFormat.java:43)
                                                                               at com.box.androidsdk.content.models.BoxJsonObject$CacheMap.getAsDate(BoxJsonObject.java:354)
                                                                               at com.box.androidsdk.content.models.BoxJsonObject.getPropertyAsDate(BoxJsonObject.java:136)
                                                                               at com.box.androidsdk.content.models.BoxUploadSession.getExpiresAt(BoxUploadSession.java:110)`

**Comment by doncung** [comment]
Can you share reproduction steps?

**Comment by PreciselyAlyss** [comment]
@kbboss Are you still running into this issue?

**Comment by PreciselyAlyss** [comment]
Please reopen if you are still encountering this issue.
