### ISSUE TITLE
Auth flow undesired behavior and internal exception

### ISSUE THREAD

**Issue by fistuk** [box/box-android-sdk#389]
When running a simple auth flow:

```
 BoxSession(context, null).apply {
            setSessionAuthListener(this)
            authenticate(context)
}
```

I'm experiencing the following undesired behavior(chronologically ordered):
1. The onAuthFailure callback is invoked with null info and exception objects.
2. Toast invoked internally in your SDK is shown: "Authentication Failed Details: -10 net::ERR_UNKNOWN_URL_SCHEME"
3. An internal caught exception appears:
```
trying to modify ImmutableBoxAuthenticationInfo: java.lang.RuntimeException
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.createFromJson(BoxAuthentication.java:784)
        at com.box.androidsdk.content.models.BoxJsonObject.<init>(BoxJsonObject.java:37)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.<init>(BoxAuthentication.java:601)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.<init>(BoxAuthentication.java:768)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.unmodifiableObject(BoxAuthentication.java:760)
        at com.box.androidsdk.content.auth.BoxAuthentication.onAuthenticated(BoxAuthentication.java:159)
        at com.box.androidsdk.content.auth.OAuthActivity.onAuthenticationChosen(OAuthActivity.java:331)
        at com.box.androidsdk.content.auth.ChooseAuthenticationFragment$1.onItemClick(ChooseAuthenticationFragment.java:49)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
        at android.widget.AbsListView$3.run(AbsListView.java:3903)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
```
4. onAuthCreated is invoked with a valid auth credentials

I would expect just the last step(onAuthCreated) to happen.

Details:
box lib version: 4.2.0

**Comment by nidoran** [comment]
Hi @fistuk , I am able to see the same error and stacktrace you posted. I will dig into this as the next step. 

I wasn't able to find 
> 2\. Toast invoked internally in your SDK is shown: "Authentication Failed Details: -10 net::ERR_UNKNOWN_URL_SCHEME"

so if you could reply where to find that or where to set a breakpoint, that might be helpful.

**Comment by fistuk** [comment]
Hi, Do you get the onAuthFailure callback before the onAuthCreated? it's a consistent behavior I have, following the failure call stack I can see it's coming from here: 
onReceivedError(OAuthWebView) -> onAuthFailure(OAuthActivity) -> 
if (failure.type == OAuthWebView.AuthFailure.TYPE_WEB_ERROR) Toast….

Some extra details:
WebView implementation - Chrome 69.0.3497.100

**Comment by doncung** [comment]
What is your redirect url as set on the developer page? Getting failure
callback is correct(as the os treats it as an error) if it is not a
standard host. The callback lets you override if necessary.

**Comment by fistuk** [comment]
You are right the problem was due to a custom non-standard redirect URI scheme. Once changing it, the flow works as expected. Going back to the failure use case, I'm overriding the failure callback, but I can't override the Toast internally invoked from the SDK, which is forced upon me in this case and can't be hidden. I would suggest giving full control to the user in such cases.
Thanks a lot for the URI scheme tip.

**Comment by nidoran** [comment]
I created https://github.com/box/box-android-sdk/pull/392 to clean up the error logging.

Will you be using the custom non-standard URI scheme in your production app? If so, can you remove the toast in com/box/androidsdk/content/auth/OAuthActivity.java ?
This use case seems not very common, so we probably will not prioritize it at this moment.

**Comment by fistuk** [comment]
We will match the URI scheme to meet your requirements. But in cases of failure(not just our case), the toast will be invoked by the SDK. We can't really remove this code as its internal SDK code and we are consuming the SDK via a Gradle dependency: 
implementation 'com.box:box-android-sdk:4.2.0'

In general, I would expect the SDK  to give a user full control over UI. Anyway thanks for the assistance.
