### ISSUE TITLE
Crash when trying to connect a second account

### ISSUE THREAD

**Issue by fistuk** [box/box-android-sdk#391]
Hi, after successfully authenticating one account and launching an authentication flow for the second time the app instantly crashes:

<img width="294" alt="screen shot 2019-02-21 at 21 25 57" src="https://user-images.githubusercontent.com/1989685/53198781-f4303280-3625-11e9-928b-58ba30c297a9.png">

Stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
        at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:6994)
        at android.widget.ListView.layoutChildren(ListView.java:1845)
        at android.widget.AbsListView.onLayout(AbsListView.java:2198)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:20676)
        at android.view.ViewGroup.layout(ViewGroup.java:6194)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2801)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2328)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:751)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by nidoran** [comment]
Hi @fistuk , is this in the "box-content-sample" app or another app?

**Comment by nidoran** [comment]
I think I found the bug now, in the "box-content-sdk". I will have a fix for this next week. Thanks

**Comment by fistuk** [comment]
Hi, Any update on this?

**Comment by nidoran** [comment]
I created a pr for the fix here: https://github.com/box/box-android-sdk/pull/395/files
Closing this issue. Thanks for the report!
Hopefully we can do a release next week with the recent fixes.
